org: moeedbhatti77
app: redpositive
service: redpositive
frameworkVersion: "3"

custom:
  esbuild:
    bundle: true
    minify: false
    packager: npm
    packagePath: /home/moeed/sideProjects/practice/package.json

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    # DYNAMO_TABLE_NAME: ${self:custom.adsTableName}
    DATABASE_NAME: ${param:DATABASE_NAME}
    MONGO_DB_URL: ${param:MONGO_DB_URL}

plugins:
  - serverless-offline
  - serverless-esbuild
functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
